extensions/iceworks-component-builder/package.json, extensions/iceworks-component-builder/web/package.json, extensions/iceworks-page-builder/web/package.json, packages/material-ui/package.json
material-ui 在 CI 中构建出来的内容有误，具体原因待排查。
当前先手动发布 `@iceworks/material-ui`，然后再手动发布相关对其有依赖的插件。
=> hotfix: publish material-ui@0.1.5

extensions/iceworks-app/CHANGELOG.md, extensions/iceworks-app/package.json, extensions/iceworks-project-creator/CHANGELOG.md, extensions/iceworks-project-creator/package.json
背景：
线上发布插件（iceworks-app & iceworks-project-creator）不成功，需要本地发布插件至插件市场
解决：
更改对应的插件的版本号
=> fix: change extensions version for publishing extensions local

README.en.md, README.md, extensions/iceworks-material-helper/README.md, extensions/iceworks-material-helper/package.json
- 仓库文档默认使用中文
- iceworks-material-help 插件的 README.md 中链接有误
=> docs: fix image link

extensions/iceworks-style-helper/CHANGELOG.md, extensions/iceworks-style-helper/README.en.md, extensions/iceworks-style-helper/README.md, extensions/iceworks-style-helper/package.json, extensions/iceworks-style-helper/src/cssClassAutoCompete/index.ts, extensions/iceworks-style-helper/src/index.ts, extensions/iceworks-style-helper/src/inlineStyleAutoComplete/index.ts, extensions/iceworks-style-helper/src/styleInfoViewer/findStyle.ts, extensions/iceworks-style-helper/src/styleInfoViewer/findStyleDependencies.ts, extensions/iceworks-style-helper/src/styleInfoViewer/findStyleSelectors.ts, extensions/iceworks-style-helper/src/styleInfoViewer/index.ts
When editing the 'class' name of a CSS, LESS or SASS file, an automatic completion reminder will be given:
Automatic completion When editing the 'style' name of a component in a JSX file, Use `cmd + click`  (Windows: `ctrl + click`) jump to the identifier under the cursor.
=> Feat add style completion

packages/generate-project/package.json, packages/generate-project/src/index.ts, packages/ice-npm-utils/package.json, packages/ice-npm-utils/src/index.ts
现在 iceworks 创建项目使用的镜像源地址是默认读取 settings.json 中的镜像源地址。如果用户是使用自定义镜像源，可能没有配置自定义镜像源，导致下载模板失败，如下图：
图来自 #胜枫（社区群）
在 `getNpmInfo` 方法中，当获取不到模板信息时候（就是地址错了），给出友好的错误提示信息
=> Feat: throw friendly error in download scaffold

extensions/iceworks-app/webpack.config.js, extensions/iceworks-component-builder/webpack.config.js, extensions/iceworks-material-import/webpack.config.js, extensions/iceworks-page-builder/webpack.config.js, extensions/iceworks-project-creator/webpack.config.js
在生产环境中开启了 source-map，构建产物过大，terser 压缩文件造成内存溢出
解决：
生产环境中不开启 source-map
=> Fix: remove source map

extensions/iceworks-project-creator/src/extension.ts
问题：
插件第二次打开失败
解决：
当关闭插件时，需将当前的 webviewPanel 设为 undefined
=> fix: project creator reopen fail

extensions/iceworks-component-builder/CHANGELOG.md, extensions/iceworks-component-builder/package.json, extensions/iceworks-component-builder/web/src/pages/Home/index.tsx, extensions/iceworks-page-builder/CHANGELOG.md, extensions/iceworks-page-builder/package.json, extensions/iceworks-page-builder/web/src/pages/Home/index.tsx
iceworks-page-builder 和 iceworks-component-builder 的物料源设置入口统一改到 Iceworks 设置面板中
效果：
=> fix: change material setting entry to Iceworks setting

extensions/iceworks-component-builder/src/i18n.ts, extensions/iceworks-component-builder/web/src/i18n.tsx, extensions/iceworks-component-builder/web/src/pages/Home/index.tsx
0. 功能完备性：支持 `@alifd/next` 的国际化：https://github.com/alibaba-fusion/next/blob/master/site/en-us/i18n.md
0. 程序正确性：loading 的初始化值为 `true`，确保获取语言包后再开始渲染
0. 程序容错性：需要有默认语言，确保语言不支持时使用默认的语言
0. 代码一致性：createIntl 方法的封装使用
=> fix: web i18n

extensions/iceworks-app/package.json, extensions/iceworks-app/webpack.config.js, extensions/iceworks-component-builder/webpack.config.js, extensions/iceworks-material-helper/webpack.config.js, extensions/iceworks-page-builder/webpack.config.js, extensions/iceworks-project-creator/webpack.config.js
问题：在 dev 环境下，使用 webpack 进行打包的插件无法进行断点调试
解决： 在 development 环境下，引入 devtool = 'source-map'，在 production 环境下不引入
=> Fix: fail to debug extension in development env

packages/material-service/package.json, packages/material-service/src/index.ts
Closed: #319
当获取应用类型为 unknown 时，默认使用 react 物料源
=> Fix: fail get material detail in unknown project

extensions/iceworks-app/package.json, extensions/iceworks-app/src/createEditorMenuAction.ts, extensions/iceworks-app/src/extension.ts, extensions/iceworks-app/src/views/nodeDependenciesView.ts, extensions/iceworks-app/src/views/npmScriptsView.ts
- 抽离 createEditorMenuAction 方法，用于注册在编辑器右上角的按钮命令（启动调试、构建项目、DEF 发布、设置入口）
- 暂时移除编辑器右上角的停止按钮（由于当前调用VSCode中的集成终端运行脚本，无法实时获取输出流  [Ref: VSCode issues](https://github.com/microsoft/vscode/issues/59384)
），这个点需要 hold 一下
=> Style: create editor menu action

packages/project-service/package.json, packages/project-service/src/index.ts
Fix:  修复在空工作区（在空工作区根路径下，没有找到 `package.json` 文件）中打开物料面板不显示默认物料的问题
=> Fix: no material display in empty workspace

extensions/iceworks-app/CHANGELOG.md, extensions/iceworks-app/src/commands/executeCommand.ts, extensions/iceworks-app/src/commands/stopCommand.ts, extensions/iceworks-app/src/createEditorMenuAction.ts, extensions/iceworks-app/src/extension.ts, extensions/iceworks-app/src/inputBoxs/showDepsInputBox.ts, extensions/iceworks-app/src/quickPicks/showDefPublishEnvQuickPick.ts, extensions/iceworks-app/src/quickPicks/showDepsQuickPick.ts, extensions/iceworks-app/src/types.ts, extensions/iceworks-app/src/views/nodeDependenciesView.ts, extensions/iceworks-app/src/views/npmScriptsView.ts
Fix: 停止脚本功能失败
解决：
- 不再维护一份 terminalsMap，直接使用 vscode.window 提供的 terminals 数组，并对其中 terminal 进行创建、销毁。
=> Fix: stop command fail

packages/page-service/package.json, packages/page-service/src/index.ts, packages/page-service/src/templates/template.rax.ts, packages/router-service/package.json, packages/router-service/src/index.ts
Fix:
- 使用Create Page添加 page 的时候，routes.ts 会忽略用 lazy 引入的原页面，又重新 import 了一遍
- Rax 搭建页面产物错误，出现 `import React, { Component } from 'react'; `
- 生成路由时引用的页面路径与文件夹名称大小写不一致 
Closed #506 
Closed #522
=> Fix: create router page path

extensions/iceworks-app/CHANGELOG.md, extensions/iceworks-app/package.json, extensions/iceworks-app/src/extension.ts, extensions/iceworks-app/src/utils/autoStart.ts, extensions/iceworks-config-helper/CHANGELOG.md, extensions/iceworks-config-helper/package.json, extensions/iceworks-doctor/CHANGELOG.md, extensions/iceworks-doctor/package.json, extensions/iceworks-material-helper/CHANGELOG.md, extensions/iceworks-material-helper/package.json, extensions/iceworks-project-creator/CHANGELOG.md, extensions/iceworks-project-creator/package.json, extensions/iceworks-style-helper/CHANGELOG.md, extensions/iceworks-style-helper/package.json, extensions/iceworks-time-steward/CHANGELOG.md, extensions/iceworks-time-steward/package.json, extensions/iceworks-ui-builder/CHANGELOG.md, extensions/iceworks-ui-builder/package.json, packages/common-service/package.json, packages/common-service/src/index.ts
调整和修复展示欢迎页的逻辑：
- 只要当前有活跃的编辑窗口，就不弹出（无论其他任何条件）
- 只有首次安装完 Iceworks 才主动弹出
- 第一次点击图标时，弹出（排除了安装完弹出的逻辑）
- 每次创建应用完成，弹出
=> hotfix: welcome page

extensions/iceworks-project-creator/CHANGELOG.md, extensions/iceworks-project-creator/package.json, packages/material-service/package.json, packages/material-service/src/index.ts
- Fix: material sources display duplicated
=> fix: material sources duplicated

packages/doctor/package.json, packages/doctor/src/getEslintReports.ts
用户老项目有相关 plugin 依赖时，eslint 找到的 plugin 会寻此地址。
更新为 @iceworks/spec 的位置，可以确保使用的都是 @iceworks/spec 指定的 plugin 和 parser.
=> Fix eslint plugin dependencies use wrong path

packages/doctor/bin/iceworks-doctor, packages/doctor/package.json, packages/doctor/src/Analyzer.ts, packages/doctor/src/Scanner.ts, packages/doctor/src/getEslintReports.ts, packages/doctor/src/getFiles.ts, packages/doctor/src/getMaintainabilityReports.ts, packages/doctor/src/index.ts, packages/doctor/src/types/Analyzer.ts, packages/doctor/src/types/File.ts, packages/doctor/src/types/Scanner.ts
doctor 支持 项目分析，可返回语言分布，示例：
```
{ languages:[
{ language: 'Other', count: 1 },
{ language: 'JSON', count: 3 },
{ language: 'Markdown', count: 1 },
{ language: 'TypeScript', count: 16 },
{ language: 'JavaScript', count: 1 } 
] }
```
=> Feat support analyse languages

extensions/iceworks-app/CHANGELOG.md, extensions/iceworks-app/package.json, extensions/iceworks-app/package.nls.json, extensions/iceworks-app/package.nls.zh-cn.json, extensions/iceworks-app/src/locales/en-US.json, extensions/iceworks-app/src/locales/zh-CN.json, extensions/iceworks-app/src/quickPicks/options.ts, extensions/iceworks-app/src/utils/createEditorMenuAction.ts, extensions/iceworks-app/src/utils/getDevServerStartInfo.ts, extensions/iceworks-app/web/src/pages/Preview/components/QRCodeWrap/index.tsx, extensions/iceworks-app/web/src/pages/Preview/index.module.scss, extensions/iceworks-app/web/src/pages/Preview/index.tsx
升级 Iceworks 预览功能：
1. 支持读取框架写入的启动 urls，超时1分钟，临时文件有效期5分钟。
2. 更新二维码展示逻辑，支持单页多页及 url 动态更新等各类情况对应展示。
3. 新增 preview 命令，并加入快捷命令中。
4. 支持天马工程预览。
=> Feat upgrade preview

packages/doctor/README.md, packages/doctor/package.json, packages/doctor/src/Analyzer.ts, packages/doctor/src/Scanner.ts, packages/doctor/src/getEslintReports.ts, packages/doctor/src/getFiles.ts, packages/doctor/src/getMaintainabilityReports.ts, packages/doctor/src/getRepeatabilityReports.ts, packages/doctor/src/index.ts, packages/doctor/src/types/Doctor.ts, packages/doctor/src/types/Scanner.ts
Doctor 支持项目 languages 分析，可读取的文件不止有 js，jsx，ts，tsx。
更新：
* getFiles 方法，返回所有文件，在不同分析函数中，区分各自支持的文件类型。
* getFiles 方法支持 .gitignore 配置
* 去除 supportExts 参数，由各个分析器决定支持的文件
=> Feat update doctor get files

extensions/iceworks-material-helper/CHANGELOG.md, extensions/iceworks-material-helper/web/src/pages/PageGenerator/index.tsx
https://github.com/ice-lab/iceworks/issues/734
=> fix: page cannot be created when block name is duplicate

extensions/iceworks-doctor/package.json, extensions/iceworks-doctor/src/extension.ts, extensions/iceworks-material-helper/CHANGELOG.md, extensions/iceworks-material-helper/package.json, extensions/iceworks-material-helper/src/componentDocSupport/openInBowser.ts, extensions/iceworks-project-creator/package.json, extensions/iceworks-project-creator/web/src/pages/CreateProject/index.tsx, packages/common-service/package.json, packages/common-service/src/index.ts, packages/constant/README.md, packages/constant/src/index.ts
之前用户信息一直存放在编辑器的配置里，这样的话用户是会在设置面板感知并且更新该信息，这不符合期望。
此次更新将用户信息存储到 iceworks 的本地设置文件。
=> refactor: save user info to iceworks configuration

scripts/o2/template/package.json
includes 字段可以在 O2 内禁止某些插件的启动，这在当套件已包含了某些插件，用户又安装了这些插件时，可以避免重复的激活。
=> feat: set includes for o2

extensions/iceworks-app/CHANGELOG.md, extensions/iceworks-app/package.json, extensions/iceworks-app/src/extension.ts, extensions/iceworks-app/src/utils/createScriptsCommands.ts, extensions/iceworks-app/src/utils/preview/autoOpenPreview.ts, extensions/iceworks-app/src/utils/preview/openPreviewWebview.ts, extensions/iceworks-app/web/src/pages/Preview/components/Header/PageSelect.tsx, extensions/iceworks-app/web/src/pages/Preview/components/Header/index.tsx, extensions/iceworks-app/web/src/pages/Preview/components/Previewer/index.tsx, extensions/iceworks-app/web/src/pages/Preview/context.ts, extensions/iceworks-app/web/src/pages/Preview/index.tsx, package.json
* 修复 手机模式切换 遗留的 ？和 & 符号
* 新增页面选择功能，可快速跳转可跳页面
* 新增自动唤起预览窗口功能，用户在 O2 环境执行 npm run start 即可自动唤起。（VS Code 环境暂时避免干扰用户）
实现原理：监听 dev.json 文件变化，执行相应逻辑
=> 更新 preview 页面

extensions/iceworks-app/.vscodeignore, extensions/iceworks-app/CHANGELOG.md
由于使用的 @iceworks/material-engine 支持按需加载，没有引用到 `prettier` 和 `@iceworks/code-generator` 两个包，因此不需要对这两个 npm 包进行 external
=> Chore: remove ignore package in iceworks-app

packages/project-utils/CHANGELOG.md, packages/project-utils/package.json, packages/project-utils/src/index.ts
getProjectTypeInfo 方法增加宽松检测模式（默认逻辑不变）
* 支持 devDependencies 中申明库的情况
* 支持 cdn 或 上层框架注入时，keywords 会申明库的情况
=> feat getProjectTypeInfo add loose mode

extensions/iceworks-project-creator/CHANGELOG.md, extensions/iceworks-project-creator/package.json, extensions/iceworks-project-creator/web/src/pages/CustomScaffold/components/ScaffoldForm/index.tsx
当用户在使用模板创建应用后，选择自定义模板创建应用。
进行配置后，点击下一步。
如果此时用户返回，则用户配置的模板数据保存，但是预览不会更新为数据的样式。
修改为 ====>
当用户返回，预览更新为用户配置的模板数据样式。
=> fix: save scaffoldValue

extensions/iceworks-doctor/CHANGELOG.md, extensions/iceworks-doctor/package.json, extensions/iceworks-doctor/package.nls.json, extensions/iceworks-doctor/package.nls.zh-cn.json, extensions/iceworks-doctor/src/extension.ts, extensions/iceworks-doctor/web/src/pages/Dashboard/components/ScanCard/index.tsx
AppWorks 平台打通 WebIDE 问题修复（O2 预发验证中，未安装插件会提示用户安装）。 
WebIDE 支持通过 url 传入运行已激活的插件指令。
* 增加 fix 命令
=> Feat doctor support fix command

extensions/iceworks-codemod/jscodeshift/package.json
iceworks-codmod 插件在上一个[版本中发布失败](https://github.com/ice-lab/iceworks/runs/2430359285?check_suite_focus=true)了：
原因是 [next-js-codemod](https://www.npmjs.com/package/next-js-codemod) 这个包依赖到了老的 recast (https://github.com/microsoft/vscode-vsce/issues/217)
recast 发了新版本修复了这个问题 (https://github.com/benjamn/recast/issues/449#issuecomment-346456022)
**next-js-codemo 新版删除了对 jscodeshift(->recast) 的依赖。**
=> fix: upgrade next-js-codemod

extensions/appworks/README.zh-CN.md, extensions/time-master/CHANGELOG.md, extensions/time-master/README.zh-CN.md, extensions/time-master/package.nls.zh-cn.json, extensions/time-master/src/locales/zh-CN.json, extensions/time-master/src/recorders/keystrokeStats/keystrokeStats.ts
为了能够更快地获取文件信息，fileChange 对象是 `onDidOpenTextDocument` 那一刻创建的；
如果没有触发 `onDidChangeTextDocument` ，则对象会没有经历 `setStart` 和 `setEnd`，因此 `start` 和 `end` 字段为空。
在发送 `KeystrokeStats` 到数据处理器时，需要确保所有 fileChange 对象都是确实 `changed`，否则数据库内会有 start/end 为 0 的记录。
=> fix: make sure that the start & end fields exist

extensions/material-helper/src/utils/getComponentSource.ts, packages/constant/CHANGELOG.md, packages/constant/package.json, packages/constant/src/index.ts, packages/material-engine/package.json, packages/material-engine/src/material/index.ts, yarn.lock
对于 `import View from 'rax-view';` 代码，node 节点上不存在 `imported` 对象，只有 `local` 对象。因此需要做区分。
=> Fix: rax component docs not display

extensions/application-manager/CHANGELOG.md, extensions/application-manager/src/locales/en-US.json, extensions/application-manager/src/locales/zh-CN.json, extensions/application-manager/src/views/nodeDependenciesView.ts
背景：点击“重装依赖”，会先删除 node_modules 目录，然后进行 npm install。但删除 node_modules 的过程中没有任何提示货反馈，需要增加 loading 的状态以获得更好的用户体验。
Preview:
=> feat: loading status when reinstalling deps

extensions/doctor/CHANGELOG.md, extensions/doctor/package.json, packages/doctor/CHANGELOG.md, packages/doctor/package.json, packages/doctor/src/workers/eslint/getEslintReports.ts
* Support add extends and plugins config.
* Fix overrides files not work,  like:
```javascript
const { getESLintConfig } = require('@iceworks/spec');
module.exports = getESLintConfig('react-ts', {
overrides: [
{
files: ['**/src/apis/**'],
rules: {
'react-hooks/rules-of-hooks': 0,
},
},
]
});
```
Because cwd is not current project path.
=> Fix overrides files not work

extensions/material-helper/src/autoFillContent/autoFillInStore.ts, extensions/material-helper/src/autoFillContent/index.ts, extensions/material-helper/src/templates/models.ts.ejs, extensions/material-helper/src/templates/store.ts.ejs
- auto fill content in store's files
- auto fill content in the files in models folder
=> feat: auto fill content in store's files

extensions/application-manager/CHANGELOG.md, extensions/application-manager/package.json, extensions/application-manager/web/src/pages/Dashboard/models/info.ts, packages/project-service/CHANGELOG.md, packages/project-service/package.json, packages/project-service/src/dependency.ts, packages/project-service/src/index.ts
Closed: https://github.com/appworks-lab/pack/issues/857
问题：在外网环境下，获取项目信息（基本信息和依赖信息）失败
- 获取依赖信息失败原因是使用 latest-version 获取依赖最新版本太慢了
- 外网环境下获取 def 信息时有请求内网地址，但没有设置超时时间
解决：
- 现在改用 package-json （支持传入 registry 地址）获取依赖最新版本
- 判断是否在外网环境下，如果是，则不去获取 def 信息
=> Fix: dashboard error

extensions/material-helper/CHANGELOG.md, extensions/material-helper/package.json, extensions/material-helper/src/importAutoComplete/getAlreadyImportSet.ts, extensions/material-helper/src/propTypesAutoComplete/getPropTypesDependentName.ts
the code in the editor is incomplete will cause the AST parser error.
When `@babel/parser errorRecovery` this option is set to true, it will store the parsing error and try to continue parsing the invalid input file.
=> fix: ast parser error

scripts/o2/config.ts
移除在 O2 上对 DEF 可视化发布插件的依赖，避免升级维护的成本
=> chore: remove @ali/publish-visual extension

extensions/material-helper/CHANGELOG.md, extensions/material-helper/package.json, extensions/material-helper/src/importAutoComplete/getAlreadyImportSet.ts, extensions/material-helper/src/mtopAutoComplete/getCurrentMtopRequestCall.ts, extensions/material-helper/src/propTypesAutoComplete/getJsxPropKeys.ts, extensions/material-helper/src/propTypesAutoComplete/getPropTypesDependentName.ts, extensions/material-helper/src/propsAutoComplete/getPropKeysFromCode.ts, extensions/material-helper/src/utils/getBabelParserPlugins.ts, extensions/material-helper/src/utils/getComponentSource.ts, extensions/material-helper/src/utils/getCurrentJsxElement.ts, extensions/material-helper/src/utils/getJsxElements.ts
=> fix: material-help

extensions/material-helper/web/mocks/material/getData.json, extensions/material-helper/web/src/pages/ComponentCreator/index.tsx, extensions/material-helper/web/src/pages/MaterialImporter/index.tsx, extensions/material-helper/web/src/pages/PageGenerator/index.tsx, extensions/material-helper/web/src/typings.d.ts, package.json, packages/common-service/src/material.ts, packages/material-engine/package.json, packages/material-engine/src/component/index.ts, packages/material-engine/src/material/constants.ts, packages/material-engine/src/material/generateDebugMaterialData.ts, packages/material-engine/src/material/getComponentTypeOptionsByProjectType.ts, packages/material-engine/src/material/getProjectComponentType.ts, packages/material-engine/src/material/index.ts, packages/material-ui/demo/usage.md, packages/material-ui/src/components/type.module.scss, packages/material-ui/src/components/type.tsx, packages/material-ui/src/components/view.tsx, packages/material-ui/src/index.tsx, packages/material-utils/src/types.ts, yarn.lock
=> Feat: support select different material

extensions/doctor/CHANGELOG.md, extensions/doctor/package.json, extensions/doctor/src/codemod.ts
Only check codemod for rax and ice project when project start
=>  feat: only check codemod for rax and ice project

packages/doctor/CHANGELOG.md, packages/doctor/package.json
@appworks/doctor 移除 ts 的依赖，使用本地的 ts 的版本进行 typescript-eslint 的检查和修复
=> chore: remove typescript dependency
