apptools-lab/AppWorks

extensions/iceworks-app/src/utils.ts
extensions/iceworks-app/src/views/npmScriptsView.ts
extensions/iceworks-component-builder/package.json
extensions/iceworks-component-builder/public/index.html
extensions/iceworks-component-builder/src/pages/Home/index.module.scss
extensions/iceworks-component-builder/src/pages/Home/index.tsx
extensions/iceworks-page-builder/public/index.html
extensions/iceworks-page-builder/src/pages/Home/components/PageSelected/index.module.scss
extensions/iceworks-page-builder/src/pages/Home/components/PageSelected/index.tsx
extensions/iceworks-page-builder/src/pages/Home/index.module.scss
extensions/iceworks-page-builder/src/pages/Home/index.tsx
packages/block-service/package.json
packages/block-service/src/index.ts
packages/common-service/src/index.ts
packages/material-ui/demo/usage.md
packages/material-ui/src/components/base.module.scss
packages/material-ui/src/components/block.module.scss
packages/material-ui/src/components/block.tsx
packages/material-ui/src/components/component.module.scss
packages/material-ui/src/components/type.module.scss
packages/material-ui/src/components/type.tsx
packages/material-ui/src/components/view.module.scss
packages/material-ui/src/components/view.tsx
packages/material-ui/src/index.scss
packages/material-ui/src/index.tsx

Page Builder:
Component Builder:

chore: style for component && page builder

---

extensions/iceworks-project-creator/package.json
extensions/iceworks-project-creator/src/pages/CreateProject/components/CreateDEFProjectForm/index.module.scss
extensions/iceworks-project-creator/src/pages/CreateProject/components/CreateDEFProjectForm/index.tsx
extensions/iceworks-project-creator/src/pages/CreateProject/components/CreateProjectForm/index.module.scss
extensions/iceworks-project-creator/src/pages/CreateProject/components/CreateProjectForm/index.tsx
extensions/iceworks-project-creator/src/pages/CreateProject/components/Header/index.tsx
extensions/iceworks-project-creator/src/pages/CreateProject/components/InitProjectSuccess/index.module.scss
extensions/iceworks-project-creator/src/pages/CreateProject/components/InitProjectSuccess/index.tsx
extensions/iceworks-project-creator/src/pages/CreateProject/components/ScaffoldMarket/index.module.scss
extensions/iceworks-project-creator/src/pages/CreateProject/components/ScaffoldMarket/index.tsx
extensions/iceworks-project-creator/src/pages/CreateProject/index.module.scss
extensions/iceworks-project-creator/src/pages/CreateProject/index.tsx
extensions/iceworks-project-creator/src/types.ts

HotFix: iceworks project creator

---

extensions/iceworks-app/src/extension.ts
extensions/iceworks-app/src/utils.ts
extensions/iceworks-app/src/views/componentsView.ts
extensions/iceworks-app/src/views/nodeDependenciesView.ts
extensions/iceworks-project-creator/package.json

Fix: fix create npm command not found

---

packages/iceworks-cli/package.json
packages/iceworks-cli/src/command/init/index.ts

Feat update rax-template source

Feat update rax-template source

---

packages/block-service/package.json
packages/common-service/package.json
packages/ice-npm-utils/package.json
packages/material-service/package.json
packages/material-ui/package.json
packages/material-utils/package.json
packages/page-service/package.json
packages/project-service/package.json
yarn.lock

feat: publish packages

---

packages/generate-project/src/fommatProject.ts

Feat add rax abc config

---

packages/generate-project/package.json
packages/generate-project/src/fommatProject.ts
packages/generate-project/src/index.ts

Update new project name and version.
Before:
name and version same as template's name and version.
After:
name: user input value
version: 0.1.0

Feat update project name

---

extensions/iceworks-component-builder/CHANGELOG.md
extensions/iceworks-component-builder/package.json
extensions/iceworks-material-helper/package.json
extensions/iceworks-page-builder/CHANGELOG.md
extensions/iceworks-page-builder/package.json
extensions/iceworks/CHANGELOG.md
extensions/iceworks/README.en.md
extensions/iceworks/README.md
extensions/iceworks/package.json
packages/vscode-webview/package.json
yarn.lock

- changelog for extensions
- change version for extensions

docs: changelog for extensions

---

.github/workflows/beta-publisher.yml

Use Regular Expressions
https://docs.travis-ci.com/user/customizing-the-build/#using-regular-expressions

Feat update beta branches

---

packages/vscode-webview/src/vscode.ts
scripts/publish-beta-extension.ts
scripts/publish-beta-package.ts
scripts/publish-extension.ts
scripts/publish-package.ts

- fix: Logger API
- fix: Beta push should use local packages

fix: logger API && Beta push

---

scripts/extension-link-package.ts
scripts/publish-beta-extension.ts
scripts/publish-beta-package.ts
scripts/publish-extension.ts
scripts/publish-package.ts

Feat add update extension dependencies beta version

Feat add update extension dependencies beta version

---

packages/material-service/src/index.ts
packages/material-ui/demo/usage.md
packages/material-ui/package.json
packages/material-ui/src/components/type.module.scss
packages/material-ui/src/components/type.tsx
packages/material-ui/src/components/view.tsx
packages/material-ui/src/index.scss
packages/material-ui/src/index.tsx
packages/project-service/package.json
packages/project-service/src/index.ts

- feat: 物料面板添加加载和为空提醒；
- fix: 项目支持 Vue https://github.com/ice-lab/iceworks/issues/111

fix: page builder

---

extensions/iceworks-project-creator/web/src/pages/CreateProject/components/CreateProjectForm/index.module.scss
extensions/iceworks-project-creator/web/src/pages/CreateProject/components/ScaffoldMarket/index.module.scss
extensions/iceworks-project-creator/web/src/pages/CreateProject/components/ScaffoldMarket/index.tsx
extensions/iceworks-project-creator/web/src/pages/CreateProject/index.module.scss

1. 修复在分辨率较低的情况下，样式出现错乱的问题
2. 增加 Loading 组件，在 scaffolds 组件加载中时

Styles: scaffolds component style 

---

.github/workflows/auto-publisher.yml
.github/workflows/beta-publisher.yml
scripts/publish-extension.ts

* Change release/* to beta branch trigger beta publish.
* Add sleep wait for npm publish and sync

Feat beta workflow and add sleep for npm publish

---

extensions/iceworks-material-helper/README.en.md
extensions/iceworks-material-helper/README.md
extensions/iceworks-material-helper/package.json
extensions/iceworks-style-helper/README.en.md
extensions/iceworks-style-helper/README.md
extensions/iceworks-style-helper/package.json
extensions/iceworks/README.en.md
extensions/iceworks/README.md
extensions/iceworks/package.json

完善以下插件的介绍说明：
- iceworks
- iceworks-material-help
- iceworks-style-help

Release 1.4.0

---

packages/project-service/package.json
packages/project-service/src/index.ts

创建项目下载 scaffold 时使用 settings.json 中的 npm registry（默认是淘宝源）

Chore: link project creator registry

---

extensions/iceworks-project-creator/CHANGELOG.md
extensions/iceworks-project-creator/package.json

本地手动发包（iceworks-project-creator），升级插件的版本号

Hotfix: upgrade project-creator version

---

extensions/iceworks-project-creator/CHANGELOG.md
extensions/iceworks-project-creator/package.json
extensions/iceworks-project-creator/web/src/components/NotFound/index.module.scss
extensions/iceworks-project-creator/web/src/components/NotFound/index.tsx
extensions/iceworks-project-creator/web/src/components/SelectCard/index.module.scss
extensions/iceworks-project-creator/web/src/pages/CreateProject/components/ScaffoldMarket/index.module.scss
extensions/iceworks-project-creator/web/src/pages/CreateProject/components/ScaffoldMarket/index.tsx
extensions/iceworks-project-creator/web/src/pages/CreateProject/index.module.scss

- 增加切换物料源时的 Loading 状态
- 增加未找到模板时默认展示状态
close: #141

feat: add scaffolds loading

---

extensions/iceworks-project-creator/web/src/pages/CreateProject/index.tsx

Fix: 修复在外网下显示 "创建 DEF 应用" 步骤
期待结果：不显示

Fix:  use project creator in external

---

package.json
scripts/publish-extension.ts
scripts/publish-package.ts

Check published packages can be installed when publish VS Code extensions.

Feat add  published packages check

---

package.json
scripts/getPackageInfos.ts
scripts/publish-beta-extension.ts
scripts/publish-beta-package.ts
scripts/publish-extension.ts
scripts/publish-package.ts
scripts/published-info.ts
scripts/upload-extensions.ts

Upload packed extension to OSS, then update extensions zip.
See:
https://github.com/ice-lab/iceworks/issues/135

Feat upload packed extension to OSS

---

.github/workflows/auto-publisher.yml

Fix extension publish failed

---

.github/workflows/auto-publisher.yml
.github/workflows/beta-publisher.yml

Fix registry taobao

---

scripts/publish-extension.ts
scripts/upload-extensions.ts

Production publish should zip all extensions.
Run pack extension before publish

Feat production publish add pack extension script

---

extensions/iceworks-style-helper/CHANGELOG.md
extensions/iceworks-style-helper/package.json
extensions/iceworks-style-helper/src/styleInfoViewer/findStyle.ts
extensions/iceworks-style-helper/src/styleInfoViewer/findStyleDependencies.ts
extensions/iceworks-style-helper/src/styleInfoViewer/findStyleSelectors.ts

* Support Ice style preview.
* Support Ice css module auto completionItem.

Feat support Ice SASS style preview

---

extensions/iceworks-style-helper/CHANGELOG.md
extensions/iceworks-style-helper/README.en.md
extensions/iceworks-style-helper/README.md
extensions/iceworks-style-helper/package.json
extensions/iceworks-style-helper/src/styleInfoViewer/index.ts

Support className style preview, definition and completion.

Feat support className

---

extensions/iceworks-component-builder/.vscodeignore
extensions/iceworks-material-import/.vscodeignore
extensions/iceworks-page-builder/.vscodeignore

Hotfix: prettier module not found

---

extensions/iceworks-app/src/quickPicks/showExtensionsQuickPick.ts
extensions/iceworks-material-import/README.en.md
extensions/iceworks-material-import/README.md

Close https://github.com/ice-lab/iceworks/issues/207

docs: material import

---

scripts/publish-extension.ts

* Change 3min to 5min.
* If sync failed exit process

Feat make wait npm sync package time longer

---

extensions/iceworks-app/CHANGELOG.md
extensions/iceworks-app/package.json
extensions/iceworks-app/web/src/constants.ts
extensions/iceworks-app/web/src/pages/ConfigHelper/index.module.scss
extensions/iceworks-app/web/src/pages/ConfigHelper/index.tsx

Close #216 
另外，增加数据加载时的 loading 状态

Fix: fail to set custom npm registry

---

extensions/iceworks-material-helper/CHANGELOG.md
extensions/iceworks-material-helper/package.json
extensions/iceworks-material-helper/src/propsAutoComplete/getPropKeysFromDefinition.ts

Fix ice component props completion, see https://github.com/ice-lab/iceworks/issues/233

Fix ice component props completion

---

extensions/iceworks-style-helper/CHANGELOG.md
extensions/iceworks-style-helper/package.json
extensions/iceworks-style-helper/src/styleInfoViewer/findStyle.ts

- Support nested CSS preview, definition and completion.
https://github.com/ice-lab/iceworks/issues/231

Feat support nesting CSS preview

---

extensions/iceworks-config-helper/.vscode/launch.json
extensions/iceworks-config-helper/.vscode/tasks.json
extensions/iceworks-config-helper/CHANGELOG.md
extensions/iceworks-config-helper/README.en.md
extensions/iceworks-config-helper/README.md
extensions/iceworks-config-helper/package.json
extensions/iceworks-config-helper/schemas/ice.build.json
extensions/iceworks-config-helper/schemas/rax.build.json
extensions/iceworks-config-helper/src/index.ts
extensions/iceworks-config-helper/tsconfig.json

Iceworks Config Helper support ICE

Feat config support ICE config

---

extensions/iceworks-project-creator/web/src/pages/CreateProject/components/CreateDEFProjectForm/index.tsx
extensions/iceworks-project-creator/web/src/pages/CreateProject/index.module.scss
extensions/iceworks-project-creator/web/src/pages/CreateProject/index.tsx

Feat: git group search and loading

---

extensions/iceworks-style-helper/tsconfig.json

Fix css-flatten d.ts error

---

extensions/iceworks-app/src/constants.ts

Fix: fail to open vue file

---

extensions/iceworks-project-creator/package.json
extensions/iceworks-project-creator/web/package.json
extensions/iceworks-project-creator/web/src/constant.ts
extensions/iceworks-project-creator/web/src/pages/CreateProject/components/ScaffoldMarket/index.tsx

Hotfix: rax scaffolds title app type icon disappear

---

extensions/iceworks-material-helper/package.json
extensions/iceworks-material-helper/src/extension.ts
extensions/iceworks-material-helper/src/i18n.ts
extensions/iceworks-material-helper/src/locales/en-US.json
extensions/iceworks-material-helper/src/locales/zh-CN.json
extensions/iceworks-material-helper/tsconfig.json
extensions/iceworks-material-helper/web/package.json
extensions/iceworks-material-helper/web/src/i18n.tsx
extensions/iceworks-material-helper/web/src/locales/en-US.json
extensions/iceworks-material-helper/web/src/locales/zh-CN.json
extensions/iceworks-material-helper/web/src/pages/Home/index.tsx
extensions/iceworks-material-helper/web/tsconfig.json

#301 同样的错误，本次尝试将 getLanguage 提前，但是并没有解决问题。
其余良好。

feat: i18n for iceworks-material-helper

---

.github/workflows/auto-publisher.yml
.github/workflows/beta-publisher.yml

Fix: 环境变量 ACCESS_KEY_ID & ACCESS_KEY_SECRET 在 `npm run setup` 中无法获取到

Fix: beta and prod publish env

---

extensions/iceworks-app/web/src/locales/en-US.json
extensions/iceworks-app/web/src/locales/zh-CN.json

fix: alert message delete-success

---

extensions/iceworks-config-helper/schemas/ice.build.json
extensions/iceworks-config-helper/schemas/rax.app.json

feat: update Json schema of ice and rax

---

.github/CONTRIBUTING.md
.github/DOCUMENT_SPECIFIC.md

https://github.com/ice-lab/iceworks/issues/286

docs: DOCUMENT SPECIFIC

---

extensions/iceworks-app/package.json
extensions/iceworks-app/src/extension.ts
extensions/iceworks-material-helper/package.json
extensions/iceworks-material-helper/src/extension.ts
extensions/iceworks-project-creator/package.json
extensions/iceworks-project-creator/src/extension.ts
extensions/iceworks-ui-builder/package.json
extensions/iceworks-ui-builder/src/extension.ts
packages/common-service/package.json
packages/common-service/src/index.ts
packages/recorder/README.md
packages/recorder/package.json
packages/recorder/src/index.ts
packages/recorder/tsconfig.json
packages/storage/README.md
packages/storage/package.json
packages/storage/src/index.ts
packages/storage/tsconfig.json
packages/vscode-webview/src/vscode.ts
tsconfig.json
yarn.lock

Logger 重构为 Recorder，并且不再依赖 vscode API

refactor: Logger to Recorder

---

extensions/iceworks-config-helper/CHANGELOG.md
extensions/iceworks-config-helper/package.json
extensions/iceworks-config-helper/schemas/rax.build.json

Feat update Config Helper rax config

---

extensions/iceworks-material-helper/CHANGELOG.md
extensions/iceworks-material-helper/package.json
extensions/iceworks-material-helper/src/propsAutoComplete/index.ts
extensions/iceworks-style-helper/CHANGELOG.md
extensions/iceworks-style-helper/package.json
extensions/iceworks-style-helper/src/cssClassAutoCompete/index.ts
extensions/iceworks-style-helper/src/index.ts
extensions/iceworks-style-helper/src/inlineStyleAutoComplete/index.ts
extensions/iceworks-style-helper/src/sassVariablesViewer/index.ts
extensions/iceworks-style-helper/src/styleInfoViewer/index.ts

Extension Style Help add recordDAU

Feat Style Help add recordDAU

---

extensions/iceworks-app/package.json
extensions/iceworks-app/src/autoSetViewContext.ts
extensions/iceworks-app/src/createEditorMenuAction.ts
extensions/iceworks-app/src/extension.ts
extensions/iceworks-app/src/locales/en-US.json
extensions/iceworks-app/src/locales/zh-CN.json
extensions/iceworks-app/src/quickPicks/showDefPublishEnvQuickPick.ts
extensions/iceworks-app/src/views/componentsView.ts
extensions/iceworks-app/src/views/nodeDependenciesView.ts
extensions/iceworks-app/src/views/npmScriptsView.ts
extensions/iceworks-app/src/views/pagesView.ts
extensions/iceworks-material-helper/src/extension.ts
extensions/iceworks-project-creator/src/extension.ts
extensions/iceworks-ui-builder/src/extension.ts
packages/common-service/package.json
packages/common-service/src/index.ts

refactor: Auto Startup

---

extensions/iceworks-project-creator/web/src/components/MobileScaffoldCard/index.module.scss
extensions/iceworks-project-creator/web/src/constant.ts
extensions/iceworks-project-creator/web/src/pages/CreateProject/components/ScaffoldMarket/index.tsx

Fix: mini program scaffold

---

extensions/iceworks-app/docs/debug.en.md
extensions/iceworks-app/docs/debug.md
packages/doctor/package.json
packages/doctor/src/getRepeatabilityReports.ts

@jscpd 包 2天前发布的版本存在问题，暂时关闭 @jscpd 相关功能，等待问题修复

Fix doctor build error

---

extensions/iceworks-style-helper/CHANGELOG.md
extensions/iceworks-style-helper/package.json
extensions/iceworks-style-helper/src/cssClassAutoCompete/index.ts
extensions/iceworks-style-helper/src/inlineStyleAutoComplete/getCompletionItem.ts
extensions/iceworks-style-helper/src/sassVariablesViewer/index.ts
extensions/iceworks-style-helper/src/styleInfoViewer/index.ts
packages/doctor/package.json
packages/doctor/src/types/Scanner.ts

https://github.com/ice-lab/iceworks/issues/410

Feat update style helper completionItem detail

---

extensions/iceworks-style-helper/CHANGELOG.md
extensions/iceworks-style-helper/package.json
extensions/iceworks-style-helper/src/cssClassAutoCompete/index.ts
extensions/iceworks-style-helper/src/index.ts
extensions/iceworks-style-helper/src/inlineStyleAutoComplete/getCompletionItem.ts
extensions/iceworks-style-helper/src/inlineStyleAutoComplete/index.ts
extensions/iceworks-style-helper/src/sassVariablesViewer/index.ts
extensions/iceworks-style-helper/src/styleInfoViewer/index.ts
packages/recorder/package.json
packages/recorder/src/index.ts

* Update recordDAU when select completionItem 
* Remove hover, definition recordDAU

Feat update Style Helper recordDAU

---

extensions/iceworks-style-helper/CHANGELOG.md
extensions/iceworks-style-helper/src/sassVariablesViewer/index.ts

Support:
```json
"themePackage": [
{
"name": "@alifd/theme-iceworks-dark"
}
]
```

Feat support theme package array

---

extensions/iceworks-app/src/createEditorMenuAction.ts
packages/common-service/src/index.ts
packages/recorder/src/index.ts

- feat: always register runBuild command
- feat: record executeCommand

feat: always register runBuild command

---

.gitignore
extensions/iceworks-app/src/debugConfig/getDefaultConfigs.ts

Fix debug ice project open chrome twice. (VS Code debugger and icejs both open Chrome)

Fix debug ice project open chrome twice

---

.gitignore
extensions/iceworks-app/CHANGELOG.md
extensions/iceworks-app/package.json
extensions/iceworks-app/src/debugConfig/getDefaultConfigs.ts
extensions/iceworks-app/src/debugConfig/index.ts

Feat support pegasus project debugger.

Feat support pegasus project debugger

---

extensions/iceworks-style-helper/.vscode/launch.json
extensions/iceworks-style-helper/.vscodeignore
extensions/iceworks-style-helper/package.json
extensions/iceworks-style-helper/webpack.config.js

Feat use webpack build style helper

Feat use webpack build style helper

---

extensions/iceworks-app/src/debugConfig/getDefaultConfigs.ts
extensions/iceworks-app/src/debugConfig/index.ts

fix  pegasus  run start --disable-open param

Fix pegasus debugger 

---

extensions/iceworks-style-helper/CHANGELOG.md
extensions/iceworks-style-helper/package.json

fix property `title` is mandatory and must be of type `string` or `object`

Fix style helper error

---

extensions/iceworks-style-helper/package.json

HotFix style helper

---

extensions/iceworks-ui-builder/CHANGELOG.md
extensions/iceworks-ui-builder/README.md
extensions/iceworks-ui-builder/README.zh-CN.md
extensions/iceworks-ui-builder/package.json
extensions/iceworks-ui-builder/src/extension.ts

Feat: support component generator dark theme

---

extensions/iceworks-project-creator/CHANGELOG.md
extensions/iceworks-project-creator/package.json

ci 打包时，没安装到 common-service 最新版本，导致打开『设置』失败

hotfix: project-creator build error

---

scripts/fn/updateExtensionDependencies.ts
scripts/publish-beta-extension.ts
scripts/publish-extension.ts

* add sleep 50000ms
* add update package version

Feat update publish script

---

scripts/publish-extension.ts

fix: extension publish

---

packages/doctor/bin/iceworks-doctor
packages/doctor/package.json
packages/doctor/src/Scanner.ts
packages/doctor/src/Scorer.ts
packages/doctor/src/getEslintReports.ts
packages/doctor/src/getFinalScore.ts
packages/doctor/src/getRepeatabilityReports.ts
packages/doctor/src/types/Scanner.ts
packages/doctor/src/types/Scorer.ts
packages/eslint-plugin-security-practices/package.json
packages/eslint-plugin-security-practices/src/configs/recommended.ts
packages/eslint-plugin-security-practices/src/rules/no-http-url.ts
yarn.lock

Add
* @iceworks/eslint-plugin-best-practices
* @iceworks/eslint-plugin-security-practices

Feat update doctor

---

extensions/iceworks-ui-builder/CHANGELOG.md
packages/component-service/package.json
packages/component-service/src/index.ts
packages/component-service/src/utils/transformTextComponent.ts

Fix:
- 生成 Text 组件样式丢失问题
- 创建组件成功后打开文件失败问题

Fix: fail to generate text component style

---

packages/eslint-plugin-security-practices/package.json
packages/eslint-plugin-security-practices/src/configs/recommended.ts

Remove  code style rules in security practices, such as tab indent.

Feat remove  code style rules in security practices

---

extensions/iceworks-ui-builder/CHANGELOG.md
extensions/iceworks-ui-builder/package.json
extensions/iceworks-ui-builder/web/package.json
extensions/iceworks-ui-builder/web/src/pages/PageCreator/configForm.tsx
extensions/iceworks-ui-builder/web/src/pages/PageGenerater/index.tsx
packages/page-service/src/index.ts
packages/router-service/package.json
packages/router-service/src/index.ts

- Fix: https://github.com/ice-lab/iceworks/pull/531/files#r487622881
- Chore: update iceworks-ui-builder version and changelog

Fix: create router pagename param

---

packages/eslint-plugin-security-practices/package.json

HotFix @iceworks/eslint-plugin-security-practices version

HotFix @iceworks/eslint-plugin-security-practices version

---

extensions/iceworks-app/src/getQuickEntryOptions.ts

Feat update dashboard command show

Feat update dashboard command show

---

scripts/fn/checkPackagePublished.ts
scripts/fn/sleep.ts
scripts/publish-beta-extension.ts
scripts/publish-extension.ts

Feat: update beta extension script

Feat: update beta extension script

---

scripts/fn/checkPackagePublished.ts
scripts/publish-beta-extension.ts

Fix CI check beta package published

Fix CI check beta package published

---

extensions/iceworks-doctor/CHANGELOG.md
extensions/iceworks-doctor/README.md
extensions/iceworks-doctor/README.zh-CN.md
extensions/iceworks-doctor/package.json
extensions/iceworks-material-helper/CHANGELOG.md
extensions/iceworks-material-helper/package.json
extensions/iceworks-material-helper/web/src/pages/Home/index.tsx
extensions/iceworks-project-creator/CHANGELOG.md
extensions/iceworks-project-creator/package.json
extensions/iceworks-project-creator/web/src/pages/CreateProject/index.tsx
extensions/iceworks-ui-builder/CHANGELOG.md
extensions/iceworks-ui-builder/package.json
extensions/iceworks-ui-builder/web/src/pages/ComponentCreator/index.tsx
extensions/iceworks-ui-builder/web/src/pages/PageCreator/index.tsx
extensions/iceworks-ui-builder/web/src/pages/PageGenerater/index.tsx
packages/material-service/package.json
packages/material-service/src/index.ts
packages/material-ui/package.json
packages/material-ui/src/index.tsx

- fix: https://github.com/ice-lab/iceworks/issues/551
- docs: add logo for Doctor

hotfix: refresh did not clean cache

---

extensions/iceworks-app/src/extension.ts
extensions/iceworks-material-helper/src/componentDocSupport/componentQuickPicks.ts
extensions/iceworks-material-helper/src/componentDocSupport/docInfoCache.ts
extensions/iceworks-material-helper/src/componentDocSupport/openInBowser.ts
extensions/iceworks-material-helper/src/extension.ts
extensions/iceworks-material-helper/src/utils/recorder.ts
packages/common-service/package.json
packages/common-service/src/index.ts
packages/recorder/package.json
packages/recorder/src/index.ts
packages/vscode-webview/package.json
packages/vscode-webview/src/vscode.ts

- 修复：当前对命名执行的打点无法快速定位是哪个命令，且缺乏命名参数的记录。
- 添加：记录 service 的调用详情
- 新增：补充部分缺失的数据采集

refactor: record

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/workflows/auto-publisher.yml
extensions/iceworks-app/CHANGELOG.md
extensions/iceworks-app/package.json
extensions/iceworks-config-helper/CHANGELOG.md
extensions/iceworks-config-helper/package.json
extensions/iceworks-doctor/CHANGELOG.md
extensions/iceworks-doctor/package.json
extensions/iceworks-material-helper/CHANGELOG.md
extensions/iceworks-material-helper/package.json
extensions/iceworks-material-helper/package.nls.json
extensions/iceworks-material-helper/package.nls.zh-cn.json
extensions/iceworks-style-helper/CHANGELOG.md
extensions/iceworks-style-helper/package.json
extensions/iceworks-time-steward/CHANGELOG.md
extensions/iceworks-time-steward/package.json
packages/common-service/package.json
packages/common-service/src/index.ts

https://github.com/ice-lab/iceworks/issues/570

hotfix: auto init material source

---

extensions/iceworks-doctor/.vscodeignore
extensions/iceworks-doctor/README.md
extensions/iceworks-doctor/README.zh-CN.md
extensions/iceworks-doctor/package.json
extensions/iceworks-doctor/scripts/minifyNodeModules.js

Feat minify Iceworks doctor

---

packages/doctor/package.json
packages/doctor/src/getEslintReports.ts
packages/eslint-plugin-security-practices/package.json
packages/eslint-plugin-security-practices/src/configs/recommended.ts

fix https://github.com/ice-lab/iceworks/issues/578

Fix doctor rules

---

extensions/iceworks-style-helper/CHANGELOG.md
extensions/iceworks-style-helper/package.json
extensions/iceworks-style-helper/src/styleInfoViewer/index.ts

Support vue class https://github.com/ice-lab/iceworks/issues/558

Feat support vue class

---

extensions/iceworks-ui-builder/CHANGELOG.md
extensions/iceworks-ui-builder/package.json
extensions/iceworks-ui-builder/web/build.plugin.js
extensions/iceworks-ui-builder/web/package.json
extensions/iceworks-ui-builder/web/src/pages/PageCreator/Editor.module.scss
extensions/iceworks-ui-builder/web/src/pages/PageCreator/Editor.tsx
extensions/iceworks-ui-builder/web/src/pages/PageCreator/configForm.tsx
extensions/iceworks-ui-builder/web/src/pages/PageCreator/index.module.scss

https://github.com/ice-lab/iceworks/issues/542

feat: Code Editor for Page Templater

---

extensions/iceworks-project-creator/CHANGELOG.md
extensions/iceworks-project-creator/package.json
packages/material-service/package.json
packages/material-service/src/index.ts

Feat: custom material sources at first

---

extensions/iceworks-app/CHANGELOG.md
extensions/iceworks-app/package.json
extensions/iceworks-app/src/locales/en-US.json
extensions/iceworks-app/src/utils/getQuickEntryOptions.ts

chore: sorting of quick entry

---

extensions/iceworks-doctor/CHANGELOG.md
extensions/iceworks-doctor/package.json

fix: iceworks-doctor.scan command

fix: iceworks-doctor.scan command

---

extensions/iceworks-doctor/CHANGELOG.md
extensions/iceworks-doctor/package.json
extensions/iceworks-doctor/src/getScanReport.ts

Fix doctor cpu

---

extensions/iceworks-ui-builder/src/debugMaterials.ts
packages/component-service/package.json

- 压缩 @iceworks/code-generator npm 包，进一步减少包体积

Chore: component-service version

---

extensions/iceworks-app/CHANGELOG.md
extensions/iceworks-app/package.json
extensions/iceworks-app/src/extension.ts
extensions/iceworks-project-creator/CHANGELOG.md
extensions/iceworks-project-creator/package.json
extensions/iceworks-project-creator/web/src/pages/CreateProject/components/ScaffoldMarket/index.tsx
packages/material-service/package.json
packages/material-service/src/index.ts

- fix: scaffolds is empty
- fix: disable auto show welcome page when the application is new

hotfix: scaffolds is empty

---

packages/vscode-generator/src/index.js
packages/vscode-generator/src/templates/extension/web/src/routes.ts

* Rename file start with  '_' like 'web/_eslintrc.js'
* Update route.ts

Fix vscode-generator beta test

---

packages/project-service/package.json
packages/project-service/src/index.ts

Feat update getProjectFramework for rax-app. add devDependencies['rax-app']

Feat update getProjectFramework for rax-app

---

extensions/iceworks-config-helper/CHANGELOG.md
extensions/iceworks-config-helper/package.json
extensions/iceworks-config-helper/schemas/ice.build.en.json
extensions/iceworks-config-helper/schemas/ice.build.zh-cn.json
extensions/iceworks-config-helper/schemas/rax.build.en.json
extensions/iceworks-config-helper/schemas/rax.build.zh-cn.json

- feat: support rax-app@3.0 build.json config
- feat: support ice.js@1.0 build.json config
https://github.com/ice-lab/iceworks/issues/617

Feat update rax and ice config schema

---

.commitlintrc.js
.eslintignore
extensions/iceworks-project-creator/web/src/global.scss
extensions/iceworks-project-creator/web/src/pages/CreateProject/components/ScaffoldMarket/index.tsx
package.json

fix: display two templates on the first screen

---

extensions/iceworks-material-helper/CHANGELOG.md
extensions/iceworks-material-helper/package.json
extensions/iceworks-material-helper/src/utils/debugMaterials.ts
packages/material-engine/package.json
packages/material-engine/src/material/generateDebugMaterialData.ts
packages/material-engine/src/menu/index.ts
packages/material-engine/src/router/index.ts

- 修复：清除本地调试物料失败
- 修复：在某些情况下调试物料源时，复制物料源到本地失败

Fix: material debug

---

extensions/iceworks-material-helper/CHANGELOG.md
extensions/iceworks-material-helper/web/src/components/RouterDetailForm/index.tsx
extensions/iceworks-material-helper/web/src/locales/en-US.json
extensions/iceworks-material-helper/web/src/locales/zh-CN.json
packages/material-engine/src/page/index.ts

closed: https://github.com/alibaba/ice/issues/3702

Feat: layout select is not necessary

---

packages/common-service/package.json
packages/config/package.json
packages/constant/package.json
packages/doctor/package.json
packages/eslint-plugin-best-practices/package.json
packages/eslint-plugin-security-practices/package.json
packages/i18n/package.json
packages/material-engine/package.json
packages/material-utils/package.json
packages/project-service/package.json
packages/project-utils/package.json
packages/recorder/package.json
packages/storage/package.json
packages/vscode-generator/package.json
packages/vscode-webview/package.json
scripts/fn/getExtensionInfos.ts
scripts/fn/getPackageInfos.ts

fix https://github.com/ice-lab/iceworks/runs/1378188460?check_suite_focus=true

refactor: build packages

---

packages/doctor/README.md
packages/doctor/bin/iceworks-doctor
packages/doctor/package.json
packages/doctor/src/Scanner.ts
packages/doctor/src/Scorer.ts
packages/doctor/src/getCustomESLintConfig.ts
packages/doctor/src/getEslintReports.ts
packages/doctor/src/getFiles.ts
packages/doctor/src/getRepeatabilityReports.ts
packages/doctor/src/index.ts
packages/doctor/src/types/Doctor.ts
packages/doctor/src/types/Scanner.ts

更新 doctor：
* 支持指定 temp 文件目录
* ESLint 报告输出详细个数信息及用户自定义配置
* 更新 scan 方法参数

Feat update doctor usage

---

extensions/iceworks-project-creator/CHANGELOG.md
extensions/iceworks-project-creator/package.json
packages/material-engine/package.json
packages/material-engine/src/material/index.ts
yarn.lock

remove icejs mini-program material

---

packages/doctor/bin/iceworks-doctor
packages/doctor/package.json
packages/doctor/src/Scanner.ts
packages/doctor/src/Timer.ts
packages/doctor/src/getEslintReports.ts
packages/doctor/src/getMaintainabilityReports.ts
packages/doctor/src/types/Scanner.ts

Feat doctor add timeout, throw timeout error,  block checker.

Feat doctor add timeout

---

packages/doctor/package.json
packages/doctor/src/getEslintReports.ts

增加 critical 级别，对应 critical error 和 critical warning。 
分数将进行翻倍，比如 warning 扣1分，则 critical warning 扣2分。
https://github.com/ice-lab/spec/pull/23

Feat add level critical

---

extensions/iceworks-app/src/utils/createEditorMenuAction.ts

Feat use 'npm run start' for debug. Remove debug in vscode.

Feat use 'npm run start' for debug 

---

packages/doctor/package.json
packages/doctor/src/Scanner.ts
packages/doctor/src/getEslintReports.ts

1. 兼容用户不传 option 
2.修复 tsconfig 文件找不到问题

fix doctor no option and no tsconfig file

---

extensions/iceworks-material-helper/CHANGELOG.md
extensions/iceworks-material-helper/package.json
extensions/iceworks-material-helper/src/services/index.ts
extensions/iceworks-material-helper/web/src/pages/PageGenerator/index.tsx
packages/material-engine/package.json
packages/material-engine/src/page/templates/template.rax.ts
packages/material-engine/src/router/index.ts
packages/project-service/package.json
packages/project-service/src/constant.ts
yarn.lock

- fix: 修复生成的 rax page 中包含 `<div>` ，应该为 `<View>` 
- feat: 创建页面时支持生成路由至 `app.json`

Feat: enhance rax

---

extensions/iceworks-doctor/.vscodeignore

fix: doctor ts not found error

fix: doctor ts not found error

---

extensions/iceworks-time-master/src/recorders/keystrokeStats/recorder.ts
extensions/iceworks-time-master/src/recorders/watchStats/recorder.ts
extensions/iceworks-time-master/src/storages/file.ts
extensions/iceworks-time-master/src/storages/project.ts
extensions/iceworks-time-master/src/storages/user.ts

- ensure current summary is correct
- ensure the consistency of data storage

fix: save summary

---

extensions/iceworks-time-master/src/extension.ts
extensions/iceworks-time-master/src/managers/data.ts
extensions/iceworks-time-master/src/managers/walkClock.ts
extensions/iceworks-time-master/src/recorders/keystrokeStats/keystrokeStats.ts
extensions/iceworks-time-master/src/recorders/keystrokeStats/recorder.ts
extensions/iceworks-time-master/src/recorders/watchStats/recorder.ts
extensions/iceworks-time-master/src/recorders/watchStats/watchStats.ts
extensions/iceworks-time-master/src/storages/file.ts
extensions/iceworks-time-master/src/storages/project.ts
extensions/iceworks-time-master/src/storages/user.ts
extensions/iceworks-time-master/src/utils/common.ts

- chore: keep some functions as private
- chore: arrangement logger.debug
- fix: async update summary logic

refactor: time-master

---

extensions/iceworks-doctor/CHANGELOG.md
extensions/iceworks-doctor/package.json
packages/doctor/package.json
packages/doctor/src/Scanner.ts
packages/doctor/src/getCustomESLintConfig.ts
packages/doctor/src/getEslintReports.ts

Fix iceworks-doctor unlink eslint cache file error, when run fix command.

Fix iceworks-doctor unlink eslint cache file error.

---

packages/doctor/bin/iceworks-doctor
packages/doctor/package.json
packages/doctor/src/Scanner.ts
packages/doctor/src/Scorer.ts
packages/doctor/src/getFinalScore.ts
packages/doctor/src/getMaintainabilityReports.ts
packages/doctor/src/getRepeatabilityReports.ts
packages/doctor/src/index.ts
packages/doctor/src/types/Scanner.ts

* 更新 jscpd 参数
* 支持设置检测重复度最大行数
* 更新评分计算方式，最低分改为10，总分改为加权平均计算。（最低分增加 0.1 权重）

Feat update score calculate

---

extensions/iceworks-doctor/CHANGELOG.md
extensions/iceworks-doctor/package.json
extensions/iceworks-doctor/src/getScanReport.ts
packages/doctor/package.json
packages/doctor/src/Analyzer.ts
packages/doctor/src/getEslintReports.ts
packages/doctor/src/getMaintainabilityReports.ts
packages/doctor/src/types/Analyzer.ts

* 支持扫码 VUE 项目
* analyse 方法支持文件个数行数信息输出

Feat support vue

---

extensions/iceworks-app/CHANGELOG.md
extensions/iceworks-app/package.json

https://github.com/ice-lab/iceworks/issues/710

feat: add menus to explorer

---

extensions/iceworks-app/package.json
extensions/iceworks-app/package.nls.json
extensions/iceworks-app/package.nls.zh-cn.json
scripts/o2/template/package.json

Closed: https://github.com/ice-lab/iceworks/issues/701

Feat: quick entry to o2

---

scripts/publish-extension.ts

fix doctor publish failed

---

extensions/iceworks-config-helper/CHANGELOG.md
extensions/iceworks-config-helper/package.json
extensions/iceworks-material-helper/CHANGELOG.md
extensions/iceworks-material-helper/package.json
extensions/iceworks-project-creator/CHANGELOG.md
extensions/iceworks-project-creator/package.json
extensions/iceworks-style-helper/CHANGELOG.md
extensions/iceworks-style-helper/package.json
extensions/iceworks-time-master/CHANGELOG.md
extensions/iceworks-time-master/package.json
extensions/iceworks-time-master/src/extension.ts
extensions/iceworks-ui-builder/CHANGELOG.md
extensions/iceworks-ui-builder/package.json
extensions/iceworks/CHANGELOG.md
extensions/iceworks/package.json
scripts/publish-extension.ts

- feat: record DAU for O2
- fix: package Doctor

Release 0.15.2

---

scripts/fn/upload-extensions.ts
scripts/publish-extension.ts

fix cli error

---

packages/common-service/src/index.ts

Ref: Issue https://github.com/ice-lab/iceworks/issues/728  PR https://github.com/ice-lab/iceworks/pull/729
今天下午在使用的时候，安装区块所需要的依赖时，也有相同的报错，之前的 PR 忘记改了，这次加上

fix(common-service): bulk install materials deps

---

packages/material-ui/demo/usage.md
packages/material-ui/package.json
packages/material-ui/src/components/view.module.scss
packages/material-ui/src/index.tsx

fix: margin right for nav scrolling

---

scripts/fn/upload-extensions.ts

Feat update upload

---

extensions/iceworks-material-helper/web/src/locales/en-US.json
extensions/iceworks-material-helper/web/src/locales/zh-CN.json
extensions/iceworks-material-helper/web/src/pages/PageGenerator/components/PageSelected/index.tsx
extensions/iceworks-material-helper/web/src/pages/PageGenerator/index.tsx

Ref: issue https://github.com/ice-lab/iceworks/issues/754

fix(iceworks-material-helper): generator page by blocks

---

extensions/iceworks-app/CHANGELOG.md
extensions/iceworks-app/package.json
extensions/iceworks-app/src/views/npmScriptsView.ts

Closed: https://github.com/alibaba/ice/issues/4045

Fix: terminal names are the same when running the scripts

---

packages/project-utils/package.json
packages/project-utils/src/index.ts

Add:
* getProjectTypeAndVersion
* getProjectFrameworkAndVersion
* getProjectLanguageType

feat: add methods

---

extensions/iceworks-time-master/CHANGELOG.md
extensions/iceworks-time-master/src/utils/env.ts
extensions/iceworks-time-master/src/utils/storage.ts

- 编辑器信息区分 O2 客户端和服务端
- 修复本地数据存储限制无效问题

fix: time master

---

extensions/iceworks-material-helper/CHANGELOG.md
extensions/iceworks-material-helper/package.json
extensions/iceworks-material-helper/web/package.json
extensions/iceworks-material-helper/web/src/pages/PageGenerator/components/PageSelected/index.tsx
extensions/iceworks-project-creator/web/src/pages/CustomScaffold/components/PageSelected/index.tsx
extensions/iceworks/CHANGELOG.md
extensions/iceworks/package.json
packages/material-ui/package.json
packages/material-ui/src/components/base.tsx
packages/material-ui/src/components/block.tsx
packages/material-ui/src/components/component.tsx
packages/material-ui/src/components/page.tsx
packages/material-ui/src/components/scaffold.tsx
packages/material-ui/src/components/type.tsx
packages/material-ui/src/components/view.tsx

material ui 得手动发，自动发布有问题。
https://github.com/ice-lab/iceworks/issues/197

fix: material panel style

---

extensions/iceworks-time-master/.vscode/launch.json
extensions/iceworks-time-master/.vscode/tasks.json
extensions/iceworks-time-master/package.json
extensions/iceworks-time-master/src/config.ts
extensions/iceworks-time-master/src/extension.ts
extensions/iceworks-time-master/src/managers/data.ts
extensions/iceworks-time-master/src/managers/walkClock.ts
extensions/iceworks-time-master/src/recorders/keystrokeStats/recorder.ts
extensions/iceworks-time-master/src/recorders/usageStats/recorder.ts
extensions/iceworks-time-master/src/utils/logger/index.ts
extensions/iceworks-time-master/src/utils/sender.ts
extensions/iceworks-time-master/src/utils/storage.ts
extensions/iceworks-time-master/src/utils/time.ts
extensions/iceworks-time-master/tsconfig.webpack.json
extensions/iceworks-time-master/webpack.config.js

- fix: check storage limit
- feat: check logs limit
- feat: send data when extension deactivate
- chore: typo
- chore: more logs

refactor: Time Master

---

extensions/iceworks-app/CHANGELOG.md
extensions/iceworks-app/src/utils/createScriptsCommands.ts
extensions/iceworks-app/src/views/nodeDependenciesView.ts
extensions/iceworks-app/web/src/pages/Dashboard/components/Framework/index.tsx
packages/common-service/package.json
packages/common-service/src/index.ts

- fix: install dependency before run debug https://github.com/ice-lab/iceworks/issues/758
- fix: upgrade dependency https://github.com/ice-lab/iceworks/issues/759

fix: bugs from issue

---

packages/project-service/package.json
packages/project-service/src/index.ts

Feat: record create project type and scaffold name

---

packages/doctor/CHANGELOG.md
packages/doctor/package.json
packages/doctor/src/Scanner.ts
packages/doctor/src/Timer.ts

修复宏任务的回调函数中的错误无法捕获，导致上层调用 try catch 无效。
修改为 微任务 错误回调，上层可 catch doctor 所有错误

fix handle timeout error

---

extensions/iceworks-time-master/CHANGELOG.md
extensions/iceworks-time-master/package.json
extensions/iceworks-time-master/src/managers/data.ts
extensions/iceworks-time-master/src/utils/common.ts
extensions/iceworks-time-master/src/utils/sender.ts
extensions/iceworks/CHANGELOG.md
extensions/iceworks/package.json
packages/user-service/CHANGELOG.md
packages/user-service/package.json
packages/user-service/src/index.ts

- 修复：推迟发送的重试应有次数限制
- 修复：获取用户信息应有超时限制
- 重构：在 O2 中使用 command 获取用户信息

hotfix: Time Master

---

extensions/iceworks-project-creator/CHANGELOG.md
extensions/iceworks-project-creator/package.json
extensions/iceworks-project-creator/web/src/pages/CreateProject/index.tsx

Fix: 创建应用，选择应用路径时，假如没有选择任何路径，会显示 undefined。

Fix: select project path undefined

---

extensions/iceworks-project-creator/CHANGELOG.md
extensions/iceworks-project-creator/package.json
extensions/iceworks-time-master/CHANGELOG.md
extensions/iceworks-time-master/package.json
extensions/iceworks-time-master/src/utils/sender.ts
extensions/iceworks/CHANGELOG.md
extensions/iceworks/package.json
packages/user-service/CHANGELOG.md
packages/user-service/package.json
packages/user-service/src/index.ts

在内网获取用户信息时不自动登录。
- 自动登录突然的弹窗交互体验差
- 自动登录失败会造成反复弹窗

hotfix: get user info

---

packages/doctor/CHANGELOG.md
packages/doctor/package.json
packages/doctor/src/Scanner.ts

unknown 项目更新为通过 @iceworks/spec 通用项目进行扫描。
https://github.com/ice-lab/spec/pull/33

feat: support unknown project

---

packages/doctor/CHANGELOG.md
packages/doctor/package.json
packages/doctor/src/Scanner.ts

feat: support scan unknown project
https://github.com/ice-lab/spec/pull/33

feat: support scan unknown project

---

extensions/iceworks-style-helper/CHANGELOG.md
extensions/iceworks-style-helper/README.md
extensions/iceworks-style-helper/README.zh-CN.md
extensions/iceworks-style-helper/package.json

feat update style helper readme

feat update style helper readme

---

extensions/iceworks-refactor/README.md
extensions/iceworks-refactor/README.zh-CN.md
extensions/iceworks-refactor/package.json

chore: refactor keybindings

---

extensions/iceworks-material-helper/CHANGELOG.md
extensions/iceworks-material-helper/package.json
packages/material-engine/CHANGELOG.md
packages/material-engine/package.json
packages/material-engine/src/menu/index.ts
packages/material-engine/src/router/index.ts
packages/material-engine/src/utils/getASTByCode.ts

Hotfix: fail to parse ts code

---

scripts/o2/package-pack.ts
scripts/publish-beta-extension.ts
scripts/publish-beta-package.ts
scripts/publish-extension.ts
scripts/publish-package.ts

Fix CI Error not exit

---

README.zh-CN.md
extensions/application-manager/web/src/locales/zh-CN.json
extensions/appworks/CHANGELOG.md
extensions/appworks/README.zh-CN.md
extensions/appworks/package.json

多端研发工具/多端研发套件 -> 前端研发工具/前端研发套件

feat: update slogan

---

extensions/application-manager/CHANGELOG.md
extensions/application-manager/package.json
extensions/codemod/CHANGELOG.md
extensions/codemod/package.json
extensions/doctor/CHANGELOG.md
extensions/doctor/package.json
extensions/material-helper/CHANGELOG.md
extensions/material-helper/package.json
extensions/project-creator/CHANGELOG.md
extensions/project-creator/package.json
packages/constant/CHANGELOG.md
packages/constant/package.json
packages/constant/src/index.ts

Chore: update webview icon

---

extensions/material-helper/CHANGELOG.md
extensions/material-helper/package.json

* change material-helper activationEvents to `onStartupFinished`
* rebuild material-helper

Chore rebuild material-helper

---

extensions/material-helper/CHANGELOG.md
extensions/material-helper/package.json

chore: rebuild Material Help

---

extensions/project-creator/CHANGELOG.md
extensions/project-creator/package.json
packages/project-service/CHANGELOG.md
packages/project-service/package.json
packages/project-service/src/index.ts

- fix: rax-spa project targets null problem. [#861](https://github.com/appworks-lab/pack/issues/861)

fix: rax-spa project targets null

---

extensions/style-helper/CHANGELOG.md
extensions/style-helper/package.json

- feat: upgrade [css](https://www.npmjs.com/package/css) fix `@media` parse failed.

Feat update css

---

extensions/application-manager/src/hintInstallTypesRax/index.ts

fix: hint install @types rax

---

extensions/style-helper/CHANGELOG.md
extensions/style-helper/src/styleInfoViewer/findStyle.ts
extensions/style-helper/src/styleInfoViewer/findStyleDependencies.ts

* support less 
* fix @media and @keyframes parse error

Fix style helper support less and fix media parse error

---

extensions/appworks/CHANGELOG.md
extensions/appworks/README.md
extensions/appworks/package.json

Use Auto Rename Tag instead to Auto Complete Tag, and fix #877

Feat remove Auto Complete Tag

---

extensions/material-helper/.vscodeignore

More info: https://github.com/microsoft/vscode-vsce/issues/588

fix .vscodeignore

---

extensions/material-helper/CHANGELOG.md
extensions/material-helper/package.json
extensions/material-helper/src/componentDocSupport/index.ts

fix command `Find Components In Current File` not working

Fix command `Find Components In Current File` not working

---

extensions/time-master/CHANGELOG.md
extensions/time-master/package.json
extensions/time-master/package.nls.json
extensions/time-master/package.nls.zh-cn.json
extensions/time-master/src/utils/sender.ts

* add time master configuration `enableDataAnalysisServices`

Feat add time master configuration

---

extensions/project-creator/.vscodeignore
extensions/react-refactor/.vscodeignore

More info: microsoft/vscode-vsce#588

Feat update vscodeignore

---

extensions/doctor/.vscodeignore
extensions/doctor/package.json
extensions/doctor/scripts/minifyNodeModules.js

Fix build error

---

extensions/application-manager/CHANGELOG.md
extensions/application-manager/package.json
packages/recorder/CHANGELOG.md
packages/recorder/package.json
packages/recorder/src/index.ts

ref: https://github.com/appworks-lab/toolkit/pull/25
该 PR 只修改 appworks/application-manager 的 @appworks/recorder 的版本，其他依赖到 @appworks/recorder 的插件和 npm 包，后续再统一升级其版本

refactor: recorder

---

extensions/doctor/CHANGELOG.md
extensions/doctor/package.json
extensions/doctor/src/codemod.ts

https://github.com/appworks-lab/codemod/pull/4

Fix empty project wrong CodeMod notice

---

extensions/project-creator/CHANGELOG.md
extensions/project-creator/package.json
extensions/project-creator/web/src/components/MobileScaffoldCard/index.tsx
extensions/project-creator/web/src/components/ScaffoldCard/index.tsx
extensions/project-creator/web/src/pages/CreateProject/components/ScaffoldMarket/index.tsx
extensions/project-creator/web/src/pages/CreateProject/index.tsx

feat: support double click to select scaffold

---

extensions/appworks/CHANGELOG.md

feat: update changelog

---

.github/O2_SPECIFIC.md
extensions/application-manager/CHANGELOG.md
extensions/application-manager/package.json
extensions/application-manager/src/locales/en-US.json
extensions/application-manager/src/locales/zh-CN.json
extensions/application-manager/src/views/nodeDependenciesView.ts
extensions/application-manager/webpack.config.js
extensions/appworks/CHANGELOG.md
extensions/appworks/package.json
extensions/doctor/CHANGELOG.md
extensions/doctor/package.json
extensions/doctor/src/codemod.ts
extensions/project-creator/CHANGELOG.md
extensions/project-creator/package.json
extensions/project-creator/web/src/components/MobileScaffoldCard/index.tsx
extensions/project-creator/web/src/components/ScaffoldCard/index.tsx
extensions/project-creator/web/src/pages/CreateProject/components/ScaffoldMarket/index.tsx
extensions/project-creator/web/src/pages/CreateProject/index.tsx
packages/recorder/CHANGELOG.md
packages/recorder/package.json
packages/recorder/src/index.ts
scripts/o2/config.ts
scripts/o2/general-pack.ts

* fix: build error in macos platform #891
* feat: support double click to select scaffold #895
* fix: empty project wrong CodeMod notice #894
* feat: loading status when reinstalling deps #896
* fix: setUserInfo service api not found #898

Release 1.2.1

---

extensions/material-helper/package.json
extensions/material-helper/snippets/snippets.json

feat: code snippets

---

extensions/material-helper/CHANGELOG.md
extensions/material-helper/package.json

- update changelog
- update version

docs: update changelog

---

extensions/appworks/CHANGELOG.md
extensions/appworks/package.json

Feat update pack changlog

---

extensions/material-helper/snippets/snippets.json

any letter that in code snippets will active the snippets when user type in vscode

fix: code snippets

---

packages/constant/CHANGELOG.md
packages/constant/package.json

feat: remove ts

---

extensions/appworks/CHANGELOG.md
extensions/appworks/package.json

stylelint will cause some bug.

fix: remove stylelint

---

extensions/application-manager/CHANGELOG.md
extensions/application-manager/package.json
packages/material-engine/CHANGELOG.md
packages/material-engine/package.json
packages/material-engine/src/material/index.ts

fix: fail to update material source

---

extensions/material-helper/CHANGELOG.md
extensions/material-helper/package.json

update the components-helper version

fix: components-helper version update

---

extensions/doctor/CHANGELOG.md
extensions/doctor/package.json
extensions/doctor/src/codemod.ts
extensions/doctor/web/mocks/action/getScanReport.ts
extensions/doctor/web/src/pages/Dashboard/components/ScanCard/components/CodemodReport/index.module.scss
extensions/doctor/web/src/pages/Dashboard/components/ScanCard/components/CodemodReport/index.tsx
packages/doctor/CHANGELOG.md
packages/doctor/bin/appworks-doctor
packages/doctor/package.json

https://github.com/appworks-lab/codemod/pull/5
* 更新 codemod 包，返回所有能运行的 codemod，由上层决定是否展示或提示用户
* doctor 扫描结果中展示所有可运行 codemod ，共用户选择。 根据 severity 展示图标
PS: 新增将 eslint 更新至 @Iceworks/spec 的 codemod。考虑到可能会影响的项目较多，将 severity 设置为0。用户启动项目时不会提示，仅在 doctor 扫描 和 发布卡口时 提示用户可用。

feat: update doctor

---

extensions/doctor/CHANGELOG.md
extensions/doctor/package.json
extensions/doctor/web/src/pages/Dashboard/components/ScanCard/components/CodemodReport/index.tsx

Support severity 0 codemod show

fix doctor show result

---

extensions/doctor/CHANGELOG.md
extensions/doctor/package.json
packages/doctor/CHANGELOG.md
packages/doctor/package.json
packages/doctor/src/getFiles.ts
packages/doctor/src/index.ts

Fix windows get empty files

---

extensions/material-helper/src/importAutoComplete/getAlreadyImportSet.ts
extensions/material-helper/src/mtopAutoComplete/getCurrentMtopRequestCall.ts
extensions/material-helper/src/propTypesAutoComplete/getJsxPropKeys.ts
extensions/material-helper/src/propTypesAutoComplete/getPropTypesDependentName.ts
extensions/material-helper/src/propsAutoComplete/getPropKeysFromCode.ts
extensions/material-helper/src/utils/getBabelParserPlugins.ts
extensions/material-helper/src/utils/getComponentSource.ts
extensions/material-helper/src/utils/getCurrentJsxElement.ts
extensions/material-helper/src/utils/getJsxElements.ts

the babel plugin's flow will cause error, when babel parse typescript files. 
- update babel plugins

fix: material-help

---

extensions/application-manager/CHANGELOG.md
extensions/application-manager/package.json
extensions/application-manager/src/views/actionsView.ts

HotFix: actions view error

---

extensions/application-manager/CHANGELOG.md
extensions/application-manager/package.json
extensions/application-manager/src/quickPicks/options.ts
extensions/application-manager/src/views/quickEntriesView.ts

feat: quick entries add 'doctor'

feat: quick entries add 'doctor'

---

extensions/doctor/CHANGELOG.md
extensions/doctor/package.json
extensions/doctor/src/codemod.ts

feat: add showInformationMessage for codemod result

 feat: add showInformationMessage for codemod result

---

extensions/appworks/CHANGELOG.md
extensions/appworks/package.json

Feat update changelog for 1.4.2

Feat update changelog for 1.4.2

---

extensions/appworks/CHANGELOG.md
extensions/appworks/package.json
extensions/doctor/CHANGELOG.md
extensions/doctor/package.json
extensions/doctor/src/codemod.ts

* feat: only check codemod for rax and ice project #969 
* feat: remove [AppWorks - CodeMod](https://marketplace.visualstudio.com/items?itemName=iceworks-team.iceworks-codemod), [Bookmarks](https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks) and [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner).  https://github.com/apptools-lab/AppWorks/issues/970

Release 1.5.1

---

extensions/style-helper/CHANGELOG.md
extensions/style-helper/src/styleInfoViewer/findStyleSelectors.ts

Fix `style={styles.xxx}` automatic completion failed with nested css file

---

extensions/style-helper/CHANGELOG.md
extensions/style-helper/package.json
extensions/style-helper/src/cssClassAutoCompete/index.ts
extensions/style-helper/src/styleInfoViewer/findStyleSelectors.ts

Add `className={styles.xxx}` automatic completion will be provided when editing css file

Feat: add `className={styles.xxx}` automatic completion

---

extensions/doctor/CHANGELOG.md
extensions/doctor/package.json
extensions/doctor/src/codemod.ts
extensions/doctor/web/src/config.ts

Doctor 插件使用 AppLint 进行检测

---

extensions/appworks/CHANGELOG.md
extensions/appworks/package.json

HotFix update AppWorks Version

HotFix update AppWorks Version

---

extensions/doctor/CHANGELOG.md
extensions/doctor/package.json

hotfix: 回退 doctor 版本

---

extensions/doctor/CHANGELOG.md
extensions/doctor/package.json

关联 PR
https://github.com/apptools-lab/AppLint/pull/45

chore: upgrade @appworks/doctor version

---

extensions/style-helper/src/cssClassAutoCompete/index.ts

fix: cursors position

---

extensions/style-helper/src/styleInfoViewer/index.ts

fix:  special object key in square brackets

---

extensions/style-helper/CHANGELOG.md
extensions/style-helper/package.json
extensions/style-helper/src/cssClassAutoCompete/index.ts
extensions/style-helper/src/styleInfoViewer/index.ts

* feat: change cursors position when auto complete the css class name. #1019 
* fix: use square brackets when class name has special  key #1020

Release 1.5.3

---

packages/generate-project/CHANGELOG.md
packages/generate-project/package.json
packages/generate-project/src/addDependenciesToPkgJson.ts
packages/generate-project/src/ejsRenderDir.ts
packages/generate-project/src/formatFileContent.ts
packages/generate-project/src/formatScaffoldToProject.ts

@iceworks/generate-project@2.x 支持使用 prettier 格式化 json 文件

feat: support format json

---

packages/generate-project/CHANGELOG.md
packages/generate-project/package.json
packages/generate-project/src/ejsRenderDir.ts

feat: support format cjs mjs cts mts file

---

packages/generate-project/CHANGELOG.md
packages/generate-project/package.json
packages/generate-project/src/__tests__/downloadAndGenerateProject.test.ts
packages/generate-project/src/formatPkgJson.ts

Remove unnecessary package.json format.

fix: remove unnecessary package.json format

---

packages/generate-project/CHANGELOG.md
packages/generate-project/package.json
packages/generate-project/src/formatPkgJson.ts

Do not remove publishConfig in package.json

fix: do not remove publishConfig in package.json
